version: "3"
services:
  prometheus-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
  grafana-server:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    restart: unless-stopped
  loki-server:
    image: grafana/loki
    ports:
      - 3100:3100 
    restart: unless-stopped
networks:
  smtp-network:
    driver: bridge